In [45]:
# import library
import torch 



a = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
a

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [34]:
points = torch.zeros(10)
points

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
points = torch.zeros(10,5)
points

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [55]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints the Y-coordinate of the zeroth point in dataset
points[0,1]

tensor(1.)

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints the X-coordinate of the second point in dataset
points[2,0]

tensor(2.)

In [59]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints Y-coordinate of zeroth point AND Y-coordinate of first point
print([points[0,1], points[1,1]])

[tensor(1.), tensor(3.)]


In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints zeroth point in dataset
points[0]

tensor([4., 1.])

In [4]:
some_list = list(range(6))
# from 1 inclusive to 4 exclusive, in steps of 2 
some_list[1:4]
# output:
# [1, 4]


[1, 2, 3]

In [5]:
some_list = list(range(6))
# from 1 inclusive to 4 exclusive, in steps of 2 
some_list[1:4:2]
# output:
# [1, 4]

[1, 3]

In [10]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data[1]

tensor([3, 4])

In [14]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data[1]

tensor([3, 4])

In [16]:
import random

coordinate_pairs = [(random.randint(0, 100), random.randint(0, 100)) for _ in range(50)]
print(coordinate_pairs)


[(99, 94), (74, 72), (57, 17), (74, 66), (10, 69), (20, 78), (96, 13), (55, 31), (53, 46), (94, 15), (60, 89), (68, 73), (39, 22), (87, 41), (87, 85), (17, 100), (34, 14), (79, 75), (54, 10), (14, 13), (50, 94), (57, 63), (64, 14), (8, 28), (83, 96), (31, 59), (62, 83), (20, 4), (73, 38), (98, 17), (19, 24), (51, 29), (16, 53), (91, 71), (87, 98), (74, 79), (77, 97), (36, 71), (83, 73), (80, 26), (91, 93), (91, 23), (11, 13), (81, 41), (70, 55), (71, 79), (3, 99), (11, 30), (97, 63), (94, 82)]


In [20]:
import torch
data = [(97, 32), (70, 67), (78, 50), (32, 0), (79, 26), (61, 40), (99, 76), (84, 42), (92, 75), (86, 46), (70, 97), (47, 96), (34, 28), (75, 76), (61, 6), (99, 38), (36, 30), (47, 44), (33, 66), (86, 8), (61, 22), (20, 50), (89, 93), (83, 55), (63, 33), (38, 80), (62, 68), (73, 84), (62, 53), (5, 4), (88, 24), (23, 23), (85, 35), (10, 58), (48, 60), (52, 15), (49, 72), (79, 5), (84, 82), (74, 79), (94, 91), (30, 56), (28, 17), (89, 86), (7, 7), (62, 49), (1, 9), (88, 38), (11, 8), (68, 72)]
x_data = torch.tensor(data)
x_data[1:43:11]

tensor([[70, 67],
        [34, 28],
        [83, 55],
        [48, 60]])

In [23]:
import torch
data = [(97, 32), (70, 67), (78, 50), (32, 0), (79, 26), (61, 40), (99, 76), (84, 42), (92, 75), (86, 46), (70, 97), (47, 96), (34, 28), (75, 76), (61, 6), (99, 38), (36, 30), (47, 44), (33, 66), (86, 8), (61, 22), (20, 50), (89, 93), (83, 55), (63, 33), (38, 80), (62, 68), (73, 84), (62, 53), (5, 4), (88, 24), (23, 23), (85, 35), (10, 58), (48, 60), (52, 15), (49, 72), (79, 5), (84, 82), (74, 79), (94, 91), (30, 56), (28, 17), (89, 86), (7, 7), (62, 49), (1, 9), (88, 38), (11, 8), (68, 72)]
x_data = torch.tensor(data)
x_data[32]

tensor([85, 35])