In [45]:
# import library
import torch 



a = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
a

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [34]:
points = torch.zeros(10)
points

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
points = torch.zeros(10,5)
points

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [55]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints the Y-coordinate of the zeroth point in dataset
points[0,1]

tensor(1.)

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints the X-coordinate of the second point in dataset
points[2,0]

tensor(2.)

In [59]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints Y-coordinate of zeroth point AND Y-coordinate of first point
print([points[0,1], points[1,1]])

[tensor(1.), tensor(3.)]


In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# prints zeroth point in dataset
points[0]

tensor([4., 1.])

In [4]:
some_list = list(range(6))
# from 1 inclusive to 4 exclusive, in steps of 2 
some_list[1:4]
# output:
# [1, 4]


[1, 2, 3]

In [5]:
some_list = list(range(6))
# from 1 inclusive to 4 exclusive, in steps of 2 
some_list[1:4:2]
# output:
# [1, 4]

[1, 3]

In [10]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data[1]

tensor([3, 4])

In [14]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data[1]

tensor([3, 4])

In [16]:
import random

coordinate_pairs = [(random.randint(0, 100), random.randint(0, 100)) for _ in range(50)]
print(coordinate_pairs)


[(99, 94), (74, 72), (57, 17), (74, 66), (10, 69), (20, 78), (96, 13), (55, 31), (53, 46), (94, 15), (60, 89), (68, 73), (39, 22), (87, 41), (87, 85), (17, 100), (34, 14), (79, 75), (54, 10), (14, 13), (50, 94), (57, 63), (64, 14), (8, 28), (83, 96), (31, 59), (62, 83), (20, 4), (73, 38), (98, 17), (19, 24), (51, 29), (16, 53), (91, 71), (87, 98), (74, 79), (77, 97), (36, 71), (83, 73), (80, 26), (91, 93), (91, 23), (11, 13), (81, 41), (70, 55), (71, 79), (3, 99), (11, 30), (97, 63), (94, 82)]


In [20]:
import torch
data = [(97, 32), (70, 67), (78, 50), (32, 0), (79, 26), (61, 40), (99, 76), (84, 42), (92, 75), (86, 46), (70, 97), (47, 96), (34, 28), (75, 76), (61, 6), (99, 38), (36, 30), (47, 44), (33, 66), (86, 8), (61, 22), (20, 50), (89, 93), (83, 55), (63, 33), (38, 80), (62, 68), (73, 84), (62, 53), (5, 4), (88, 24), (23, 23), (85, 35), (10, 58), (48, 60), (52, 15), (49, 72), (79, 5), (84, 82), (74, 79), (94, 91), (30, 56), (28, 17), (89, 86), (7, 7), (62, 49), (1, 9), (88, 38), (11, 8), (68, 72)]
x_data = torch.tensor(data)
x_data[1:43:11]

tensor([[70, 67],
        [34, 28],
        [83, 55],
        [48, 60]])

In [1]:
import torch
data = [(97, 32), (70, 67), (78, 50), (32, 0), (79, 26), (61, 40), (99, 76), (84, 42), (92, 75), (86, 46), (70, 97), (47, 96), (34, 28), (75, 76), (61, 6), (99, 38), (36, 30), (47, 44), (33, 66), (86, 8), (61, 22), (20, 50), (89, 93), (83, 55), (63, 33), (38, 80), (62, 68), (73, 84), (62, 53), (5, 4), (88, 24), (23, 23), (85, 35), (10, 58), (48, 60), (52, 15), (49, 72), (79, 5), (84, 82), (74, 79), (94, 91), (30, 56), (28, 17), (89, 86), (7, 7), (62, 49), (1, 9), (88, 38), (11, 8), (68, 72)]
x_data = torch.tensor(data)
x_data[32]

tensor([85, 35])

In [3]:
# We move our tensor to the GPU if available
import torch
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

# forward pass
prediction = model(data)
loss = (prediction - labels).sum()
loss.backward() #backward pass

optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step() #gradient descent

In [2]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
import numpy as np 
array = np.array([1,2,3,4,5])

In [10]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)

print(array.shape)

[1 2 3 4 5]
(5,)


In [11]:
import torch
tensor = torch.tensor([1,2,3,4,5])
print(tensor)

print(tensor.shape)

tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [32]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)
print(array.shape)
array

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
import torch
tensor = torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(tensor)
print(tensor.shape)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# numpy

zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# numpy

zeros = np.zeros((100, 100))
print(zeros)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
zeros = torch.zeros(3, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
# pytorch
import torch
zeros = torch.zeros(10, 10)
print(zeros)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [26]:
import torch
tensor = torch.zeros(10,10)
print(tensor)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [29]:
import torch
varNet1 = torch.ones(12, 12)
print(varNet1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [34]:
ones = np.ones((3,3))
print(ones)
ones

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# pytorch 

one = torch.ones(3,3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
# NumPy random

import numpy as np
random_array = np.random.rand(3, 3)
print(random_array)

[[0.58145262 0.02073443 0.83558531]
 [0.57931346 0.31004113 0.03610814]
 [0.60063958 0.12346073 0.98534972]]


In [40]:
import numpy as np
array = np.random.rand(10, 10)
array

array([[0.9349597 , 0.02520715, 0.46688687, 0.59182272, 0.5748897 ,
        0.77042855, 0.14286566, 0.99032512, 0.45705169, 0.10837924],
       [0.70823562, 0.75943382, 0.55674758, 0.34459014, 0.1888052 ,
        0.92044335, 0.28421279, 0.84075479, 0.02430928, 0.82357717],
       [0.83554743, 0.1749574 , 0.45263401, 0.07703226, 0.60914074,
        0.94603289, 0.95855062, 0.49480305, 0.04796718, 0.06093929],
       [0.50818834, 0.64302229, 0.55611258, 0.54987791, 0.77720244,
        0.89176572, 0.96209536, 0.52107699, 0.72345632, 0.23768148],
       [0.56622125, 0.40366209, 0.19480312, 0.12483635, 0.38018609,
        0.75197128, 0.20897258, 0.30856452, 0.91512363, 0.25314296],
       [0.23160158, 0.87888811, 0.98845779, 0.45625881, 0.12304857,
        0.23476271, 0.19536179, 0.04368922, 0.86648987, 0.07330765],
       [0.27264828, 0.09202904, 0.28532726, 0.95308326, 0.41417187,
        0.4715007 , 0.03854304, 0.4799072 , 0.9158616 , 0.31801793],
       [0.13870239, 0.98847544, 0.1798319

In [43]:
import numpy as np
randar = np.array((10, 10))
print(randar)

[10 10]


In [47]:
import torch 
tensor = torch.rand(3,3)
print(tensor)
print(tensor.shape)
tensor

tensor([[0.9813, 0.3465, 0.7476],
        [0.1846, 0.3892, 0.3010],
        [0.5217, 0.7261, 0.4324]])
torch.Size([3, 3])


tensor([[0.9813, 0.3465, 0.7476],
        [0.1846, 0.3892, 0.3010],
        [0.5217, 0.7261, 0.4324]])

In [49]:
# pytorch random tensor creation

import torch
random_tensor = torch.rand(10, 10)
print(random_tensor)
print(random_tensor.shape)
random_tensor

tensor([[0.1753, 0.0449, 0.0927, 0.3132, 0.2772, 0.6372, 0.1225, 0.1596, 0.7369,
         0.0729],
        [0.8774, 0.4082, 0.6708, 0.6121, 0.9472, 0.9164, 0.7945, 0.0166, 0.5801,
         0.1140],
        [0.8064, 0.6564, 0.0131, 0.1672, 0.2322, 0.3537, 0.3276, 0.1538, 0.9231,
         0.8660],
        [0.7648, 0.9107, 0.2891, 0.1368, 0.7365, 0.4041, 0.3233, 0.8082, 0.2484,
         0.0428],
        [0.2353, 0.9971, 0.3976, 0.0784, 0.1347, 0.4087, 0.9737, 0.6730, 0.6600,
         0.3043],
        [0.4620, 0.4891, 0.5447, 0.2082, 0.1720, 0.9116, 0.7959, 0.8535, 0.6738,
         0.0093],
        [0.1914, 0.2536, 0.0304, 0.7675, 0.2753, 0.0447, 0.7941, 0.3325, 0.6314,
         0.9938],
        [0.0582, 0.4157, 0.4561, 0.0497, 0.6932, 0.8772, 0.4570, 0.2729, 0.5616,
         0.0121],
        [0.9262, 0.0113, 0.0756, 0.3102, 0.1878, 0.8236, 0.0930, 0.9016, 0.4584,
         0.3303],
        [0.3395, 0.3490, 0.7461, 0.2174, 0.0688, 0.8274, 0.7064, 0.9932, 0.5117,
         0.1115]])
torch.Siz

tensor([[0.1753, 0.0449, 0.0927, 0.3132, 0.2772, 0.6372, 0.1225, 0.1596, 0.7369,
         0.0729],
        [0.8774, 0.4082, 0.6708, 0.6121, 0.9472, 0.9164, 0.7945, 0.0166, 0.5801,
         0.1140],
        [0.8064, 0.6564, 0.0131, 0.1672, 0.2322, 0.3537, 0.3276, 0.1538, 0.9231,
         0.8660],
        [0.7648, 0.9107, 0.2891, 0.1368, 0.7365, 0.4041, 0.3233, 0.8082, 0.2484,
         0.0428],
        [0.2353, 0.9971, 0.3976, 0.0784, 0.1347, 0.4087, 0.9737, 0.6730, 0.6600,
         0.3043],
        [0.4620, 0.4891, 0.5447, 0.2082, 0.1720, 0.9116, 0.7959, 0.8535, 0.6738,
         0.0093],
        [0.1914, 0.2536, 0.0304, 0.7675, 0.2753, 0.0447, 0.7941, 0.3325, 0.6314,
         0.9938],
        [0.0582, 0.4157, 0.4561, 0.0497, 0.6932, 0.8772, 0.4570, 0.2729, 0.5616,
         0.0121],
        [0.9262, 0.0113, 0.0756, 0.3102, 0.1878, 0.8236, 0.0930, 0.9016, 0.4584,
         0.3303],
        [0.3395, 0.3490, 0.7461, 0.2174, 0.0688, 0.8274, 0.7064, 0.9932, 0.5117,
         0.1115]])

In [61]:
# NumPy tensor operations

import numpy as np

array1 = np.zeros((4,4))
array2 = np.ones((4,4))
print("Array 1")
print(array1)
print("")
print("Array 2")
print(array2)

result = np.add(array1, array2)
print("")
print("Array 1 + Array 2")
print(result)


Array 1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array 1 + Array 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [63]:
# pytorch tensor operation
import torch
tensor1 = torch.zeros(4,4)
tensor2 = torch.ones(4,4)
result = torch.add(tensor1,tensor2)
print(result)



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [70]:
import numpy as np
tensor1 = np.array((4,4))
reshaped = tensor1.reshape(1, 2)
print(tensor1)
print(reshaped)


[4 4]
[[4 4]]


In [74]:
import torch
tensor1 = torch.tensor([4, 4])
reshaped = tensor1.view(1,2)
print(tensor1)
print(reshaped)

tensor([4, 4])
tensor([[4, 4]])


In [ ]:
# Python: Import necessary libraries/modules
# PyTorch: Import PyTorch and its submodules
import torch
import torch.nn as nn
import torch.nn.functional as F

# Python: Define a class that inherits from another class
# PyTorch: Define a neural network class that inherits from nn.Module
class GenericNet(nn.module):

    # Python: Constructor method for class initialization
    # PyTorch: Initialize neural network layers
    def __init__(self):
        # Python: Call constructor of parent class
        # PyTorch: Initialize the parent nn.Module class
        super(GenericNet, self).__init__()

        # Python: Assign attributes to the class instance
        # PyTorch: Define convolutional layers
        self.conv_layer1 = nn.Conv2d(1, 6, 5)
        self.conv_layer2 = nn.Conv2d(6,15,5)
        
        # PyTorch: Define fully connected (dense) layers

    # Python: Define a method for the class
    # PyTorch: Define the forward pass of the neural network

        # PyTorch: Apply convolution, activation function, and pooling
        
        # Python: Transform data
        # PyTorch: Flatten tensor for fully connected layers
        
        # PyTorch: Apply fully connected layers with activation functions

# Python: Create an instance of a class
# PyTorch: Instantiate the neural network
net = GenericNet()
# Python: Print the representation of an object
print(GenericNet)
